package modelo.entidade;
// Generated 11/06/2023 17:21:51 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Curso generated by hbm2java
 */
public class Curso  implements java.io.Serializable {


     private int codigo;
     private String nome;
     private String area;
     private Date duracao;
     private String cadeira;
     private byte[] videoaula;

    public Curso() {
    }

    public Curso(int codigo, String nome, String area, Date duracao, String cadeira, byte[] videoaula) {
       this.codigo = codigo;
       this.nome = nome;
       this.area = area;
       this.duracao = duracao;
       this.cadeira = cadeira;
       this.videoaula = videoaula;
    }
   
    public int getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(int codigo) {
        this.codigo = codigo;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public String getArea() {
        return this.area;
    }
    
    public void setArea(String area) {
        this.area = area;
    }
    public Date getDuracao() {
        return this.duracao;
    }
    
    public void setDuracao(Date duracao) {
        this.duracao = duracao;
    }
    public String getCadeira() {
        return this.cadeira;
    }
    
    public void setCadeira(String cadeira) {
        this.cadeira = cadeira;
    }
    public byte[] getVideoaula() {
        return this.videoaula;
    }
    
    public void setVideoaula(byte[] videoaula) {
        this.videoaula = videoaula;
    }




}


